# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newsApp
  pod "SwiftyJSON"
  pod "Alamofire", "~> 4.9.1"
  pod "Toast-Swift", "~> 4.0.0"
  pod "SwiftSpinner"
  pod "Charts"
  pod "XLPagerTabStrip", "~> 9.0"
end
